import { Title, UnderlineInput } from "@/components/common";
import { FactorSelectionModal } from "@/components/quant/FactorSelectionModal";
import {
  ConditionCard,
  FieldPanel,
  SectionHeader,
} from "@/components/quant/ui";
import { useFactorsQuery } from "@/hooks/useFactorsQuery";
import { useSubFactorsQuery } from "@/hooks/useSubFactorsQuery";
import { useBacktestConfigStore } from "@/stores";
import Image from "next/image";
import { useEffect, useState, useRef } from "react";
import { useShallow } from "zustand/react/shallow";

/**
 * 매수 조건식 설정 섹션
 * - 조건식 목록 관리
 * - 논리 조건식 작성
 * - 매수 종목 선택 우선순위 (팩터 선택 모달 사용)
 */
export function BuyConditionsSection() {
  // ✅ useShallow hook 사용 (데이터와 함수 분리)
  const { buyConditionsUI, buy_logic, priority_factor, priority_order } =
    useBacktestConfigStore(
      useShallow((state) => ({
        buyConditionsUI: state.buyConditionsUI,
        buy_logic: state.buy_logic,
        priority_factor: state.priority_factor,
        priority_order: state.priority_order,
      })),
    );

  // 함수들은 별도로 선택 (안정적인 참조)
  const addBuyConditionUI = useBacktestConfigStore(
    (state) => state.addBuyConditionUI,
  );
  const updateBuyConditionUI = useBacktestConfigStore(
    (state) => state.updateBuyConditionUI,
  );
  const removeBuyConditionUI = useBacktestConfigStore(
    (state) => state.removeBuyConditionUI,
  );
  const setBuyLogic = useBacktestConfigStore((state) => state.setBuyLogic);
  const setPriorityFactor = useBacktestConfigStore(
    (state) => state.setPriorityFactor,
  );
  const setPriorityOrder = useBacktestConfigStore(
    (state) => state.setPriorityOrder,
  );

  const { data: subFactors = [] } = useSubFactorsQuery();
  const { data: factors = [] } = useFactorsQuery();

  // 모달 상태
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [currentConditionId, setCurrentConditionId] = useState<string | null>(
    null,
  );

  // 우선순위 팩터 선택 모달 상태
  const [isPriorityModalOpen, setIsPriorityModalOpen] = useState(false);
  const [priorityFactorDisplay, setPriorityFactorDisplay] =
    useState<string>("");

  // 논리식 자동 생성 모드 (기본값: true)
  const [isAutoLogic, setIsAutoLogic] = useState(true);

  // 초기 기본값 설정 완료 여부 (race condition 방지)
  const initialDefaultSetRef = useRef(false);

  // 우선순위 팩터 기본값 설정 (컴포넌트 최초 마운트 시 1회만)
  // AI 헬퍼에서 priority_factor를 설정하면 이후 기본값으로 덮어쓰지 않음
  useEffect(() => {
    // 이미 초기 기본값 설정이 완료되었으면 무시 (AI 헬퍼 등 외부에서 설정 시 덮어쓰기 방지)
    if (initialDefaultSetRef.current) return;

    const hasExistingValue = priority_factor && priority_factor.length > 0;

    if (hasExistingValue) {
      // 이미 값이 있으면 초기화 완료로 표시하고 종료
      initialDefaultSetRef.current = true;
      return;
    }

    if (factors.length > 0) {
      // PER 팩터를 기본값으로 설정 (최초 1회만)
      const defaultFactor = factors.find((f) => f.name === "per") || factors[0];
      if (defaultFactor) {
        setPriorityFactor(`기본값({${defaultFactor.display_name}})`);
        setPriorityFactorDisplay(`기본값({${defaultFactor.display_name}})`);
        initialDefaultSetRef.current = true;
      }
    }
  }, [factors, priority_factor, setPriorityFactor]);

  // 스토어 priority_factor 변경 시 표시 텍스트 동기화
  useEffect(() => {
    if (priority_factor) {
      const cleaned = priority_factor.replace(/[{}]/g, "");
      setPriorityFactorDisplay(cleaned);
    }
  }, [priority_factor]);

  // 논리 조건식 자동 생성
  useEffect(() => {
    if (isAutoLogic) {
      if (buyConditionsUI.length > 0) {
        // 조건 ID들을 추출하여 "A and B and C" 형식으로 생성
        const conditionIds = buyConditionsUI.map((c) => c.id);
        const autoGeneratedLogic = conditionIds.join(" and ");
        setBuyLogic(autoGeneratedLogic);
      } else {
        // 조건이 없으면 빈 문자열
        setBuyLogic("");
      }
    }
  }, [buyConditionsUI, isAutoLogic, setBuyLogic]);

  // 모달 열기
  const openModal = (id: string) => {
    setCurrentConditionId(id);
    setIsModalOpen(true);
  };

  // 모달 닫기
  const closeModal = () => {
    setIsModalOpen(false);
    setCurrentConditionId(null);
  };

  // 팩터 선택
  const handleFactorSelect = (
    _factorId: string,
    factorName: string,
    subFactorId: string,
    argument?: string,
  ) => {
    if (!currentConditionId) return;

    const subFactor = subFactors.find((sf) => String(sf.id) === subFactorId);
    const subFactorName = subFactor?.display_name || null;

    updateBuyConditionUI(currentConditionId, {
      factorName,
      subFactorName,
      argument,
    });

    closeModal();
  };

  // 연산자 변경
  const handleOperatorChange = (id: string, operator: string) => {
    updateBuyConditionUI(id, { operator });
  };

  // 값 변경
  const handleValueChange = (id: string, value: string) => {
    updateBuyConditionUI(id, { value });
  };

  // 조건식 텍스트 생성
  const getConditionExpression = (condition: any) => {
    if (!condition.factorName) return "팩터를 선택하세요";

    let text = "";
    if (condition.subFactorName) {
      text = condition.argument
        ? `${condition.subFactorName}({${condition.factorName}},{${condition.argument}})`
        : `${condition.subFactorName}({${condition.factorName}})`;
    } else {
      text = condition.factorName;
    }

    return `${text} ${condition.operator} ${condition.value || "___"}`;
  };

  // 현재 조건 가져오기
  const getCurrentCondition = () => {
    if (!currentConditionId) return undefined;
    const condition = buyConditionsUI.find((c) => c.id === currentConditionId);
    if (!condition) return undefined;

    return {
      factorName: condition.factorName || undefined,
      subFactorName: condition.subFactorName || undefined,
      argument: condition.argument,
    };
  };

  // 우선순위 팩터 선택
  const handlePriorityFactorSelect = (
    _factorId: string,
    factorName: string,
    subFactorId: string,
    argument?: string,
  ) => {
    // subFactorId로 subFactorName 찾기
    const subFactor = subFactors.find((sf) => String(sf.id) === subFactorId);
    const subFactorName = subFactor?.display_name;

    // 팩터 표현식 생성
    let expression = "";
    let displayText = "";
    if (subFactorName) {
      if (argument) {
        expression = `${subFactorName}({${factorName}},{${argument}})`;
        displayText = `${subFactorName}({${factorName}},{${argument}})`;
      } else {
        expression = `${subFactorName}({${factorName}})`;
        displayText = `${subFactorName}({${factorName}})`;
      }
    } else {
      expression = `{${factorName}}`;
      displayText = factorName;
    }

    setPriorityFactor(expression);
    setPriorityFactorDisplay(displayText);
    setIsPriorityModalOpen(false);
  };

  return (
    <div id="section-buy-conditions" className="space-y-3">
      <SectionHeader title="매수 조건 설정" />

      <FieldPanel conditionType="buy">
        <div className="space-y-10">
          {/* 매수 조건식 설정 */}
          <div>
            <Title variant="subtitle" className="mb-3">
              매수 조건식 설정
            </Title>

            {/* 조건 목록 */}
            <div className="space-y-2 mb-2">
              {buyConditionsUI.map((condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  expressionText={getConditionExpression(condition)}
                  onFactorSelect={() => openModal(condition.id)}
                  onOperatorChange={(op) =>
                    handleOperatorChange(condition.id, op)
                  }
                  onValueChange={(val) => handleValueChange(condition.id, val)}
                  onRemove={() => removeBuyConditionUI(condition.id)}
                  conditionType="buy"
                />
              ))}
            </div>

            {/* 조건 추가 버튼 */}
            <button
              type="button"
              onClick={addBuyConditionUI}
              className="w-[31.25rem] h-12 flex items-center gap-3 rounded-md border-[0.5px] relative"
            >
              {/* plus 아이콘 */}
              <div className="">
                <Image
                  src="/icons/plus.svg"
                  alt=""
                  width={48}
                  height={48}
                  className="rounded-tl-md rounded-bl-md"
                />
              </div>

              {/* 텍스트 */}
              <div className="text-tag-neutral">
                조건식을 추가하려면 클릭하세요.
              </div>

              {/* 삭제 아이콘 */}
              <Image
                src="/icons/trash.svg"
                alt=""
                width={24}
                height={24}
                className="absolute right-3 opacity-30"
              />
            </button>
          </div>

          {/* 논리 조건식 */}
          <div>
            <div className="flex justify-between items-center w-[31.25rem] mb-3">
              <Title variant="subtitle">논리 조건식 작성</Title>
              <button
                type="button"
                onClick={() => setIsAutoLogic(!isAutoLogic)}
                className={`px-3 py-1 rounded-md text-sm transition-colors ${isAutoLogic
                  ? "bg-price-up text-white"
                  : "bg-price-up-soft hover:bg-gray-300"
                  }`}
              >
                {isAutoLogic ? "🤖 자동" : "✏️ 수동"}
              </button>
            </div>
            <UnderlineInput
              placeholder="A and B"
              value={buy_logic}
              onChange={(e) => {
                setBuyLogic(e.target.value);
                // 수동 입력 시 자동 모드 해제
                if (isAutoLogic) {
                  setIsAutoLogic(false);
                }
              }}
              disabled={isAutoLogic}
              className={`w-[31.25rem] ${isAutoLogic ? "bg-gray-50 cursor-not-allowed" : ""
                }`}
            />
            {isAutoLogic && buyConditionsUI.length > 0 && (
              <p className="text-sm text-text-neutral mt-2">
                💡 조건이 추가/삭제되면 자동으로 생성됩니다
              </p>
            )}
          </div>

          {/* 매수 종목 선택 우선순위 */}
          <div>
            <div className="flex justify-between w-[31.25rem] mb-3">
              <Title variant="subtitle">매수 종목 선택 우선순위</Title>
              <div className="flex gap-4 justify-center items-center">
                <div className="flex justify-center items-center">
                  <button
                    type="button"
                    onClick={() => setPriorityOrder("desc")}
                    className={`${priority_order === "desc"
                      ? "text-text-strong"
                      : "text-tag-neutral"
                      }`}
                  >
                    높은 값부터
                  </button>
                  <Image
                    src="/icons/arrow_down.svg"
                    alt=""
                    width={16}
                    height={16}
                    className={`${priority_order === "desc" ? "opacity-100" : "opacity-30"
                      }`}
                  />
                </div>
                <div className="flex justify-center items-center">
                  <button
                    type="button"
                    onClick={() => setPriorityOrder("asc")}
                    className={`${priority_order === "asc"
                      ? "text-text-strong"
                      : "text-tag-neutral"
                      }`}
                  >
                    낮은 값부터
                  </button>
                  <Image
                    src="/icons/arrow_up.svg"
                    alt=""
                    width={16}
                    height={16}
                    className={`${priority_order === "asc" ? "opacity-100" : "opacity-30"
                      }`}
                  />
                </div>
              </div>
            </div>
            <div
              onClick={() => setIsPriorityModalOpen(true)}
              className="w-[31.25rem] p-[14px] border-[0.5px] border-tag-neutral rounded-md cursor-pointer hover:border-accent-primary"
            >
              {priorityFactorDisplay ||
                priority_factor ||
                "팩터를 선택해주세요"}
            </div>
          </div>
        </div>
      </FieldPanel>

      {/* 매수 조건식 팩터 선택 모달 */}
      <FactorSelectionModal
        isOpen={isModalOpen}
        onClose={closeModal}
        onSelect={handleFactorSelect}
        initialValues={getCurrentCondition() as any}
      />

      {/* 우선순위 팩터 선택 모달 */}
      <FactorSelectionModal
        isOpen={isPriorityModalOpen}
        onClose={() => setIsPriorityModalOpen(false)}
        onSelect={handlePriorityFactorSelect}
      />
    </div>
  );
}
